- hosts: localhost
  tasks:
   - name: Test that my module works
     json:
       filepath: example.json
       jsonpath: "Students"
       search: "Chemistry"
       value: "Name"
     register: result

   - debug: var=result
