- hosts: localhost
  tasks:
   - name: Basic example using example1
     json_file:
       filepath: example1.json
       jsonpath: Students
       search: Major=Chemistry
       value: Name
     register: result1a

   - debug: var=result1a

   - name: Basic example using example1
     json_file:
       filepath: example1.json
       jsonpath: Students
       search: Major=Physics
       value: Name
     register: result1b

   - debug: var=result1b

   - name: Basic example using example1
     json_file:
       filepath: example1.json
       jsonpath: Students
       search: Name=Rajeev Sen
       value: Major
     register: result1c

   - debug: var=result1c

   - name: Intermediate example using example2
     json_file:
       filepath: example2.json
       jsonpath: list,weather
       search: dt=1446940800,id=501
       value: main
     register: result2a

   - debug: var=result2a

   - name: Intermediate example using example2
     json_file:
       filepath: example2.json
       jsonpath: list,weather
       search: dt=1446940800,id=501
       value: description
     register: result2b

   - debug: var=result2b
