- hosts: localhost
  tasks:
   - name: Basic example using example1
     json:
       filepath: example1.json
       jsonpath: Students
       search: "Major=Chemistry"
       value: Name
     register: result1a

   - debug: var=result1a

   - name: Basic example using example1
     json:
       filepath: example1.json
       jsonpath: Students
       search: "Major=Physics"
       value: Name
     register: result1b

   - debug: var=result1b

  #  - name: Advanced example using example2
  #    json:
  #      filepath: example2.json
  #      jsonpath: "['_embedded']['episodes']['images']"
  #      search: fsdkfdkl
  #      value: Name
  #    register: result2
   #
  #  - debug: var=result2
