- hosts: localhost
  tasks:
   - name: Test that my module works
     json:
       filepath: example.json
       jsonpath: "['sample']['someitem']"
       value: "['neat']"
     register: result

   - debug: var=result
